### ISSUE TITLE
We need csrf_exempt support.

### ISSUE THREAD

**Issue by sameerjagtap** [vapor-community/CSRF#13]
We need csrf_exempt support like django has. I have a login API (POST) in which i am creating csrf token, but its asking for csrf token even before creating.
https://docs.djangoproject.com/en/3.0/ref/csrf/

**Comment by 0xTim** [comment]
Is this for an API or website?

**Comment by sameerjagtap** [comment]
Login API

**Comment by 0xTim** [comment]
So do you want to protect the Login POST request with a CSRF token or is it other endpoints that you want protected?

**Comment by 0xTim** [comment]
(Side note - what exactly are you trying to protect against? Is this an API consumed by an SPA or is it used by an iOS app for example)

**Comment by sameerjagtap** [comment]
Suppose I don't want to protect Login API (POST).  How can i do that? adding [.POST] to ignoredMethods will not work, because it will br applied to all POST API's. Currently there is no provision to exempt particular API from CSRF checks.

**Comment by 0xTim** [comment]
The simple way is to just not add the middleware to that route.

As an aside, if you're not using a browser to interact with your API, CSRF really doesn't make any sense, or provide any protection

**Comment by sameerjagtap** [comment]
How can i do that in Vapor 3?

**Comment by 0xTim** [comment]
Well if you're adding the middleware globally, change that to add it to a route group and add the routes to that instead. This would be better asked in Vapor Discord

**Comment by sameerjagtap** [comment]
ok, thanks. I will try this.
