### ISSUE TITLE
CSRF constructor is internal

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor-community/CSRF#2]
There is no way to create CSRF instance as init is internal

https://github.com/vapor-community/CSRF/blob/master/Sources/CSRF.swift#L20

**Comment by mdmathias** [comment]
Thanks! I released [a patch](https://github.com/vapor-community/CSRF/releases/tag/1.0.1) fixing this.

**Comment by Igor-Palaguta** [comment]
Thanks,

Can you please make all HTTPMethod's (.GET) also public

https://github.com/vapor-community/CSRF/blob/master/Sources/CSRF.swift#L156

**Comment by mdmathias** [comment]
Yes, of course. Sorry for that oversight.

[Here is a release](https://github.com/vapor-community/CSRF/releases/tag/1.0.2) with that patch.

**Comment by Igor-Palaguta** [comment]
Cool! Thanks!
